### PR TITLE
Fix CI job

### PR DESCRIPTION
**Pull request by theogf**
Attempt to fix CI after #20

### CODE REVIEW

**Comment by thomvet** [comment]
Tests are calling Makie and opening a figure; this only works when a monitor is present or when setting headless. 
An example is shown here: https://github.com/MakieOrg/Makie.jl/blob/e5ace3b80659472b6b9ca9111d157c07a771ed87/.github/workflows/Docs.yml#L47

See also here: https://docs.makie.org/dev/explanations/headless

**Comment by theogf** [comment]
> Tests are calling Makie and opening a figure; this only works when a monitor is present or when setting headless. An example is shown here: https://github.com/MakieOrg/Makie.jl/blob/e5ace3b80659472b6b9ca9111d157c07a771ed87/.github/workflows/Docs.yml#L47
> 
> See also here: https://docs.makie.org/dev/explanations/headless

That makes sense, it seems they only test on Linux though. We could just disable MacOS and Windows tests here?

**Comment by thomvet** [comment]
Awesome job fixing this!

**Comment by theogf** [comment]
@stelmo This should be ready to be merged! Do you think you could tag a new release at the same time?

**Comment by stelmo** [comment]
Hi there! Really sorry about the delay, I was writing a grant :) Will merge and release asap

**Pull request merged**
